version: "3.3"
services:
  score_webtop:
    image: lscr.io/linuxserver/webtop:latest
    container_name: score_webtop
    mem_limit: 2G
    mem_reservation: 128M
    cpus: 2
    ports:
      - 8181:8181
      - 3000:3000
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Johannesburg
    volumes:
      - ./config:/config
      - ./score:/score
    restart: unless-stopped