spring:
  application:
    name: judge
  cloud.config.enabled: false
  thymeleaf: # Thymeleaf
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
  resources: # Static resources
    static-locations: file:src/main/resources/static/
    cache:
      period: 0

spring.application.name=JUDGE
# actuator
management:
  endpoints.web.exposure.include: health,info
  info.env.enabled: true
info:
  application.name: ${spring.application.name}

# Multipart file upload
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# Logging
# Root
logging.level.root=info
logging.level.za.co.imac=info
